var level1 = { "height":16,
 "layers":[
        {
         "compression":"zlib",
         "data":"eJxjYBgFAwnaB9oBo2AUDCKwGI3fNiCuQAVTaWCmGg3MHAW0AXMH2gFIYAKUngilJ5GgF1+aK4PS5SS7iIFBG0rbkaEXFyiB0qUE1BGKG1h4kRJOgxVQEkcDAUgJ+8EQT9RwAzYzrCgwbxTQBwylvLV0oB1AZTCaP\/CD0bYibhABpSOhdBSUjh4At5ACPElQS0z+GErlF7WBCpn6sMUBKfEy2AC2NADLFyloNHI+WQtlo9PE2oEOYPFBTD1FbHjD+hg6UFoXSW4w1B\/0yH9pUDqDyuYOtjRPbHqE9RHDoDShvuJgAOjpGFt6pjYgN38sICC\/kExzBxMAAKrOIwk=",
         "encoding":"base64",
         "height":16,
         "name":"platforms",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":100,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJzt00ENACAMA8D5lwMGsQBJyQK5E7D10VYBAK+Y3QEgLNnpEbx1yja5Idnpzn10\/oYd9gEA\/1o+pQZG",
         "encoding":"base64",
         "height":16,
         "name":"ladders",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":100,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "properties":
    {

    },
 "renderorder":"right-down",
 "tileheight":35,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tileset.png",
         "imageheight":1024,
         "imagewidth":1024,
         "margin":2,
         "name":"tileset",
         "properties":
            {

            },
         "spacing":2,
         "tilecount":196,
         "tileheight":70,
         "tilewidth":70
        }],
 "tilewidth":35,
 "version":1,
 "width":100
}